language: java
sudo: false
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

notifications:
  email:
    - cdi-dev@lists.jboss.org
  irc:
    channels:
      - "chat.freenode.net#cdi-dev"
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always